struct Content: Contentable {
    var id: String
    var uri: String?
    var title: String
    var contentType: ContentType
    var thumbnail: String?
    var channelId: String?
    var tvChannel: TVChannel?
    var channelUri: String?
    var callSign: String?
    var genre: String
    var startTime: TimeInterval?
    var endTime: TimeInterval?
    var resources: [String]?
    var duration: Int
    var bookmarkPosition: Int
    var closedCaptioning: Bool?
    var description: String
    var sap: Bool?
    var showType: String?
    var hd: Bool
    var isFavorite: Bool
    var seriesId: String?
    var seasonId: String?
    var programId: String?
    var seasonUri: String?
    var seasonNumber: Int?
    var episodeNumber: Int?
    var images: [ContentImage]
    var parentalLevel: ParentalLevel
    var relatedRatings: RelatedRatings?
    var credits: Credit
    var releasedYear: Int
}
